{% set name = "pytest-notebook" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1dc5c1b86209bd47b2ea6ee214467fba57102ef1e88903ea56f86625e37f403

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.7
    - flit >=3.2,<4
  run:
    - attrs
    - black
    - jsonschema
    - nbclient ~=0.5.10
    - nbdime
    - nbformat
    - pytest >=3.5.0
    - python >=3.7

test:
  imports:
    - pytest_notebook
    - pytest_notebook.diffing
    - pytest_notebook.example_nbs
    - pytest_notebook.execution
    - pytest_notebook.ipy_magic
    - pytest_notebook.nb_regression
    - pytest_notebook.notebook
    - pytest_notebook.plugin
    - pytest_notebook.post_processors
    - pytest_notebook.resources
    - pytest_notebook.utils
  commands:
    - pytest -h

about:
  home: https://github.com/chrisjsewell/pytest-notebook
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A pytest plugin for testing Jupyter Notebooks
  doc_url: https://pytest-notebook.readthedocs.io

extra:
  recipe-maintainers:
    - chrisjsewell
    - xmnlab
