{% set name = "pytest_notebook" %}
{% set version = "0.9.0" %}

package:
  name: pytest_notebook
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eea3e8ba7b0232e84a0c8ce72e02a7c28bc5a340ea41e61d97c6f05b8813d665

build:
  number: 0

outputs:
  - name: pytest_notebook
    build:
      noarch: python
      script: 'python -m pip install . --no-deps --ignore-installed -vv '
    requirements:
      host:
        - pip
        - python >=3.7
        - flit >=3.2,<4
      run:
        - attrs
        - black
        - jsonschema
        - nbclient ~=0.5.10
        - nbdime
        - nbformat
        - pytest >=3.5.0
        - python >=3.7
        - importlib-resources ~=5.0
    test:
      requires:
        - pip
      imports:
        - pytest_notebook
      commands:
        - pip check
        - pytest -h

  # see https://github.com/conda-forge/importlib_metadata-feedstock/blob/main/recipe/meta.yaml
  - name: pytest-notebook
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('pytest_notebook', max_pin="x.x.x") }}
    test:
      imports:
        - pytest_notebook

about:
  home: https://github.com/chrisjsewell/pytest-notebook
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A pytest plugin for testing Jupyter Notebooks
  doc_url: https://pytest-notebook.readthedocs.io

extra:
  recipe-maintainers:
    - chrisjsewell
    - xmnlab
